#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test, or to a directory using the glob pattern.

set -e

cd "$(dirname "$0")/.."

echo "==> Linting files..."
if [ -n "$1" ]; then
  # pass arguments to standard. This is useful for checking a single JavaScript file, 
  # or a directory using the glob pattern. 
  # You can also pass in --fix to fix lint errors.
  npx standard "$@"
else
  npx standard
fi
